name: Release Snapshot
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Release to snapshots repository
      run: mvn deploy -q --file pom.xml --settings src/devops/.release.settings.xml -Denv.OSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }} -Denv.OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}
